<?php
use PHPUnit\Framework\TestCase;

include dirname(__DIR__) . "/vendor/autoload.php";

/**
 * Created by IntelliJ IDEA.
 * User: r
 * Date: 2017/8/14
 * Time: 上午1:02
 */
class TestReport extends TestCase
{
    public function testPushAndPop()
    {
        $activityId = time();
        $userBehavior = new \YuanFen\UserBehavior($activityId, "testingEvent", "testingCookie");
        $behaviorReport = new \YuanFen\BehaviorClient(getenv("YFX_KEY"), getenv("YFX_SECRET"), getenv("YFX_SID"));

        $result = $behaviorReport->postEvent($userBehavior);
        $this->assertEquals(true, $result);
    }

    protected function setUp()
    {
        $dotenv = new Dotenv\Dotenv(__DIR__);
        $dotenv->load();
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}